name: scoreboard_desktop
description: Football and basketball scoreboard for Windows, MacOS and Linux.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  fluent_ui: ^4.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  go_router: ^6.0.4
  google_fonts: ^3.0.1
  intl: ^0.17.0
  local_api:
    path: packages/local_api
  local_api_remote:
    path: packages/local_api_remote
  local_repository:
    path: packages/local_repository
  match_api:
    path: packages/match_api
  match_api_remote:
    path: packages/match_api_remote
  match_repository:
    path: packages/match_repository
  shared_preferences: ^2.0.15
  window_manager: ^0.2.9

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  msix: ^3.7.0
  very_good_analysis: ^3.1.0

assets:
  - assets/

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: false
  ios: false
  image_path: "assets/logo.png"
  web:
    generate: false
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  linux:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256

msix_config:
  display_name: Scoreboard Desktop
  publisher_display_name: Piero Angelo Morales Alcalde
  identity_name: 29622PieroAngeloMoralesAl.ScoreboardDesktop
  publisher: CN=91BE0923-E8F6-4F62-AE9E-2A123C9AC1AF
  msix_version: 1.0.2.0
  languages: es-es
  logo_path: assets/logo.png
  capabilities: internetClient
  store: true
